version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.8:
          context: pip-staging
#      - test-3.7
#      - test-3.6
jobs:
  test-3.6: &test-template
    environment:
      PATH: /root/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    docker:
      - image: python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install deps
          command: |
            pip install -q --user --upgrade -r requirements.txt
            python setup.py develop --prefix ~/.local --no-deps
      - run:
          name: Build stats
          command: |
            echo TERM = $TERM
            mkdir -p  build-stats
            pipdeptree | tee  build-stats/pipdeptree.txt
            pip list | tee  build-stats/pip-list.txt
            pip freeze | tee  build-stats/pip-freeze.txt
            env | tee  build-stats/env.txt
      - store_artifacts:
          path: build-stats
          destination:  build-stats
      - run:
          name: Run tests
          command: |
            pip install -q --user nose
            PATH=~/.local/bin:$PATH ~/.local/bin/nosetests comptests.unittests
      - run:
          name: CodeCov
          when: always
          command: |
            bash <(curl -s https://codecov.io/bash)

  test-3.7:
    <<: *test-template
    docker:
      - image: python:3.7
  test-3.8:
    <<: *test-template
    docker:
      - image: python:3.8
